use_frameworks!

platform :ios, '10.0'

target 'MKBeaconPirSensor_Example' do
  pod 'MKBeaconPirSensor', :path => '../'

  target 'MKBeaconPirSensor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
